### ISSUE TITLE
As a new player, I want to be able to create a profile/account with chosen credentials (username and password).

### ISSUE THREAD

**Issue by thomi100** [sopra-fs23-group-40/Server#1]
### Front-End
- [x] sopra-fs23-group-40/Client#4
- [x] sopra-fs23-group-40/Client#7

### Back-End
- [x] sopra-fs23-group-40/Server#31 
- [x] sopra-fs23-group-40/Server#32
- [x] sopra-fs23-group-40/Server#33

## Acceptance Criteria:
- [x] On the “home screen” an user can register by clicking on the “register button”.
- [x] As an already registered user, a user can log-in into their profile.
Upon registering or logging in, one can see the overview page.
- [x] Logged-in (only registered users) users can log-out and log back into the registered profile.
- [x] There should be an error when a player tries to register with an already chosen username and the password/username fields cannot be empty.

**Comment by Karo2222** [comment]
bf7a776aca7576e26961980efc35b73fe7521cdc

**Comment by thomi100** [comment]
This issue can be closed as all subtasks have been completed and the acceptance criteria is met. For the commits, please relate to the subtasks.
