### ISSUE TITLE
As a logged in user, I want be able to create a gamelobby, for other players to join.

### ISSUE THREAD

**Issue by thomi100** [sopra-fs23-group-40/Server#2]
### Front-End:
- [x] sopra-fs23-group-40/Client#22
- [x] sopra-fs23-group-40/Client#23
- [x] sopra-fs23-group-40/Client#20
- [x] sopra-fs23-group-40/Client#21

### Back-End:
- [x] sopra-fs23-group-40/Server#38

## Acceptance Criteria:
As a logged in user:
- [x] I want to click on a 'create' button to create a new lobby.
- [x] I want to be redirected into my own lobby.
- [x] I want to be able to switch between a public and private lobby by clicking a button.
- [x] In a private lobby I want to have a passcode which I can share with friends, so they can join my lobby.
- [x] In a public lobby I want other people to be able to join without any extra steps.
