### ISSUE TITLE
As a user, I want to see a list of open lobbies, which I can join by clicking on it.

### ISSUE THREAD

**Issue by turbodumba** [sopra-fs23-group-40/Server#21]
### Front-end
- [ ]  sopra-fs23-group-40/Client#3

### Back-end
- [ ]  sopra-fs23-group-40/Server#26 
- [ ]  sopra-fs23-group-40/Server#30

## Acceptance criteria
As a logged in user I want to:
- [x]  See available lobbies on the overview screen
- [x]  See the name of the each lobby.
- [x]  See if a lobby is public or private.
- [x]  Be able to click on a lobby to try to join it.
- [x]  Directly join the lobby if it is public and I click it.
- [x]  Get redirected to another screen if it is private, where I have to input a passcode.
