### ISSUE TITLE
As a player during the game, I want to be able to select/move/rotate my pieces while it's my turn, in order to fulfill my turn.

### ISSUE THREAD

**Issue by turbodumba** [sopra-fs23-group-40/Server#22]
## Front-end:
- [x] sopra-fs23-group-40/Client#9
- [x] sopra-fs23-group-40/Client#11
- [x] sopra-fs23-group-40/Client#12
- [x] sopra-fs23-group-40/Client#13

## Back-end:
- [x]  sopra-fs23-group-40/Server#35
- [x] sopra-fs23-group-40/Server#42
- [x] #44 
- [x] #75
- [x] #101

### Acceptance Criteria:
As a Player:
- [x]  I want to choose a block in my inventory.
- [x]  I want to be able to rotate & flip this block.
- [x]  I want to be able to choose where to put the block (either drag/drop or defined points).
- [x]  I want to confirm my choice.

**Comment by thomi100** [comment]
closing because all subtasks have been completed and the acceptance criteria is met
