### ISSUE TITLE
As a logged-in user, I want to click on "menu" in the top right corner on the overview screen and see the menu bar.

### ISSUE THREAD

**Issue by Karo2222** [sopra-fs23-group-40/Server#34]
### Front-End
- [ ] sopra-fs23-group-40/Client#14
- [ ] sopra-fs23-group-40/Client#15
- [ ] sopra-fs23-group-40/Client#16
- [ ] sopra-fs23-group-40/Client#17
### Acceptance Criteria
- [ ] After logging in and seeing the overview screen, I want to click on "menu" in the top right corner.
- [ ] After clicking on menu, the menu bar should be visible with the options to log-out, go to the profile or look at the rules.

**Comment by thomi100** [comment]
This user Story is completed as all Front-End tasks have been completed and the Acceptance Criteria is met.
